Side Bar Functionality
Zhangjason308/SYSC-4806-Project pull request #46
Opened 2024-11-23 05:21 UTC by Nervith

This makes the sidebar, and the basics of the logged in function

2024-11-23 05:28 UTC, Waluiyeegi commented on .idea/Untitled.iml
When pushing try not to push any of idea files, so just push the files that you changed and leave the idea files on your local device.

2024-11-23 05:28 UTC, Waluiyeegi commented on .idea/modules.xml
same as above

2024-11-23 05:29 UTC, Waluiyeegi commented on server/target/classes/Main.class
i think we dont wanna push anything in the target files as well

2024-11-23 20:13 UTC, Zhangjason308 requested changes
Merge main into your branch. Its currently outdated since we add alot of new changes

2024-11-23 20:13 UTC, Zhangjason308 commented on client/src/App.svelte
>  <script>
You shouldn't mutate the App.Svelte file
We use a router

2024-11-23 20:13 UTC, Zhangjason308 commented on client/src/components/Dashboard.svelte
> +<script>
shouldn't need this dashboard

2024-11-23 20:13 UTC, Zhangjason308 commented on server/target/classes/Main.class
yeah please undo the unneeded file pushes like /target and /idea

2024-11-25 01:07 UTC, nicholasyung1 commented on .idea/modules.xml
Agreed, should only be submitting .Java, .JS, .Svelte files

2024-11-25 01:08 UTC, nicholasyung1 commented on client/src/components/MainLayout.svelte
> +    let isLoggedIn = true; // Simulated login state
Should remove testing materials when merging to main.

2024-11-25 01:09 UTC, nicholasyung1 commented on client/src/components/MainLayout.svelte
> +            <Route path="/" component={Home} />
I think this already exists in router.Svelte file.

@Zhangjason308, please confirm

2024-12-02 04:59 UTC, closed without merging